# Generated by Django 4.2.1 on 2023-05-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_options_post_user_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.CharField(max_length=25, verbose_name='Имя'),
        ),
    ]
