# Generated by Django 4.2.1 on 2023-05-22 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_user_post_author_alter_comments_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Коментария')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='post/images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
